apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: my-app-secrets
  data:
  - secretKey: DB_USERNAME
    remoteRef:
      key: my-app/db-credentials
      property: username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: my-app/db-credentials
      property: password